### ISSUE TITLE
对嘤嘤饭的迫害什么时候才能真正停止？？

### ISSUE THREAD

**Issue by SEALchanPS** [PatriciaOfEnd/PatriciaOfEnd.github.io#1]
气抖冷这个社会还能不能好了
~~我们~~ 你们对嘤嘤饭的迫害什么时候才能停止 ~~愈演愈烈~~
**气抖冷嘤嘤饭站不起来了！！！**（
```batch
@echo off
:yyfbiss
echo yyfbiss
goto yyfbiss
::嘤嘤饭给👴爬
exit
```
噔噔咚（（

**Comment by ParanoiaSeal** [comment]
@PatriciaOfEnd 出来看 issue（

**Comment by ParanoiaSeal** [comment]
> #Living on dick of YYF
> Modern computer science takes cosmos's "this is a lying working group.". The expectations originated from paranoia seal and mathematics are losing their significance. But in the face of the seemingly boundless future sky, I think it is better to follow sealchan "nobody loves China better than me.".
> Our passionate soul is naturally endowed with the pursuit of transcendence, disdaining the constraints of the old coordinates and loving the fragrance of other places. However, when this expectation becomes a criticism of batchism without thinking, and even moves towards Patricia and non Dick doctrine, it is worthy of vigilance. The difference and dislocation with the order can never be used as a basis for the behavior of overstepping the moment. Even though we have a detailed blueprint, we still can't hold ourselves. We have set our own anchor on the top of the tide.
> "I don't have a dick.". People of the same sex are inseparable, and we want to go to the green cloud all the time because of the wind. Mathematics and paranoia seal have been regarded as a symbol object of thin ridge for the time being. To some extent, it is because we lack experience and experience to support our cognition. The pride of prejudice is more than the pride of knowledge.
> On the road of striving for the significance of computer science, my expectation is the dynamic process of molding in the docking with mathematics and paranoia seal. Our base material is the perception and recognition of different subjects' pohaiing Ying Ying fan 'and different cutting Ying Ying fan's dick. Feng Yikang sent for Ying Ying fan to nobody knows and maintained Doki Doki. His concept of computer science is solid and practical. If we "enchant" the expanding self after borrowing the words of "participant of end" in the past, we will lose the expectation of the outside world, and at the same time, we will not lose ourselves.
> There is no doubt that from the perspective of paranoia seal's science and mathematics, one target's self is somewhat biased and outdated. But what we should abandon is not the criticism, but the cheapness of the criticism and the anti intellectual tendency in his devotion to criticism. In sealchan's concept, if we omit the process of carrying the legacy of our predecessors like a camel before becoming a lion and a child, then his "eternal repetition" will not hold water.
> In the end, the gap in the blueprint is only the difference in concept, and the distinction in the field of practice may not be clear. For example, when we pursue does Ying Ying fan have a dick, we set foot in I love Patricia forever on the way. Is this accompanied by the death of expectation or the achievement of expectation? As we shape computer science, computer science is casting us. We can not deny the original heterosexual and androgyny, but also admit that there is frivolous distortion in your own picture. We may as well let the experience go before the words. Taste the sea and sails of Patricia of end with an unbounded mind, and keep silent on the unspeakable things with the help of participa of end.
> The way of life used in YYF's dick embodies the transcendence of individual, keeping upright but not rigidly attached to the so-called one-dimensional image of "leaving the world behind and independent". This is the ideal expectation paradigm provided by participa of end. Live on the dick of YYF - always love the earth - rise to the sky.
